/**
 *  Copyright (C) 2008-2013  Telosys project org. ( http://www.telosys.org/ )
 *
 *  Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, Version 3.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *          http://www.gnu.org/licenses/lgpl.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.telosys.tools.generator.context;

import java.util.List;

import org.telosys.tools.commons.TelosysToolsLogger;
import org.telosys.tools.commons.variables.Variable;
import org.telosys.tools.generator.Generator;
import org.telosys.tools.generator.GeneratorException;
import org.telosys.tools.generator.GeneratorVersion;
import org.telosys.tools.generator.config.GeneratorConfig;
import org.telosys.tools.generator.context.doc.VelocityMethod;
import org.telosys.tools.generator.context.doc.VelocityObject;
import org.telosys.tools.generator.context.names.ContextName;
import org.telosys.tools.generator.target.TargetDefinition;
import org.telosys.tools.repository.model.Entity;
import org.telosys.tools.repository.model.RepositoryModel;

/**
 * Embedded generator stored in the Velocity Context and usable in the template.
 * 
 * @author Laurent GUERIN
 *
 */
//-------------------------------------------------------------------------------------
@VelocityObject(
		contextName= ContextName.GENERATOR ,
		text = "Embedded generator usable in a template to generate another target ",
		since = "2.0.3"
 )
//-------------------------------------------------------------------------------------
public class EmbeddedGenerator {

	private final RepositoryModel    repositoryModel ;
	private final GeneratorConfig    generatorConfig ;
	private final TelosysToolsLogger logger ;
	private final List<String>       selectedEntitiesNames;	
	private final boolean            canGenerate ;
	private final List<Target>       generatedTargets ;
	
	/**
	 * Constructor for limited generator without generation capabilities
	 */
	public EmbeddedGenerator() {
		super();
		this.repositoryModel = null ;
		this.generatorConfig = null ;
		this.logger = null ;
		this.selectedEntitiesNames = null ;
		this.canGenerate = false ;
		this.generatedTargets = null ;
	}

	/**
	 * Constructor for real generator that can generate sub-targets from a template
	 * @param repositoryModel
	 * @param generatorConfig
	 * @param logger
	 * @param selectedEntitiesNames
	 * @param generatedTargets
	 */
	public EmbeddedGenerator(	RepositoryModel repositoryModel,
								GeneratorConfig generatorConfig, 
								TelosysToolsLogger logger, 
								List<String> selectedEntitiesNames,
								List<Target> generatedTargets) {
		super();
		this.repositoryModel = repositoryModel;
		this.generatorConfig = generatorConfig;
		this.logger = logger;
		if ( repositoryModel != null && generatorConfig != null && logger != null ) {
			this.canGenerate = true ;
		}
		else {
			this.canGenerate = false ;
		}
		this.selectedEntitiesNames = selectedEntitiesNames ;
		this.generatedTargets = generatedTargets ;
	}

	//-------------------------------------------------------------------------------------
	@VelocityMethod(
		text={	
			"Returns the generator's name "
			},
		example = {
			"// Generated by $generator.name "
		}
	)
	public String getName()
	{
		return "Telosys Tools Generator";
	}
	
	//-------------------------------------------------------------------------------------
	@VelocityMethod(
		text={	
			"Returns the generator's version "
			},
		example = {
			"// Generator version : $generator.version "
		}
	)
	public String getVersion()
    {
        return GeneratorVersion.GENERATOR_VERSION ;
    }
	
	//-------------------------------------------------------------------------------------
	@VelocityMethod(
		text={	
			"Generates an other target with the given template file "
			},
		parameters = { 
			"entityName : the name of the entity",
			"outputFile : the file name to be generated ",
			"outputFolder : the folder where to generate the file",			
			"templateFile : the template file to be used "			
			},
		example = {
			"#if ( $entity.hasCompositePrimaryKey() )",
			"$generator.generate($target.entityName , \"${entity.name}Key.java\", $target.folder, \"jpa_bean_pk.vm\" ) ",
			"#end"
		}
	)
	public void generate(String entityName, String outputFile, String outputFolder, String templateFile) throws GeneratorException
	{
		String err = "Cannot generate with embedded generator ";
		
		if ( canGenerate != true ) {
			throw new GeneratorException( err + "(environment not available)");
		}
		
		if ( null == entityName ) {
			throw new GeneratorException( err + "(entity name is null)");
		}
		if ( null == outputFile ) {
			throw new GeneratorException( err + "(output file is null)");
		}
		if ( null == outputFolder ) {
			throw new GeneratorException( err + "(output folder is null)");
		}
		if ( null == templateFile ) {
			throw new GeneratorException( err + "(template file is null)");
		}
		
		//ProjectConfiguration projectConfiguration = generatorConfig.getProjectConfiguration();
		Variable[] allVariables = generatorConfig.getTelosysToolsCfg().getAllVariables(); // v 2.1.0
		
		Entity entity = repositoryModel.getEntityByName(entityName.trim());
		if ( null == entity ) {
			throw new GeneratorException( err + "(entity '" + entityName + "' not found in repository)");
		}
		
		TargetDefinition genericTarget = new TargetDefinition("Dynamic target", outputFile, outputFolder, templateFile, "");
		
		//Target target = new Target( genericTarget, entity.getName(), entity.getBeanJavaClass(), projectConfiguration.getAllVariables() );
		Target target = new Target( genericTarget, entity.getName(), entity.getBeanJavaClass(), allVariables ); // v 2.1.0
		
		//Generator generator = new Generator(target, generatorConfig, logger);
		Generator generator = new Generator(target, generatorConfig, repositoryModel, logger); // v 2.0.7
		
		generator.generateTarget(target, repositoryModel, selectedEntitiesNames, this.generatedTargets);
		
	}
	
}
