
/*
 * Created on 24 févr. 2014 ( Time 16:22:39 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a composite Primary Key  

/******
keyAttributes size = 2
nonKeyAttributes size = 2
bigList size = 4
. bookOrderId - Integer
. bookId - Integer
. quantity - Integer
. price - BigDecimal
******/
package GENERATED_FILES;

/*

*/
import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Persistent class for entity stored in table "BOOK_ORDER_ITEM"
 *
 * @author Telosys Tools Generator
 *
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="BOOK_ORDER_ITEM", schema="ROOT" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="AaaaBookOrderItemFoo.query1", query="SELECT x FROM AaaaBookOrderItemFoo x WHERE  " ),
//  @NamedQuery ( name="AaaaBookOrderItemFoo.query2", query="SELECT x FROM AaaaBookOrderItemFoo x WHERE  " )
// } )
public class AaaaBookOrderItemFoo implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private AaaaBookOrderItemFooKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="QUANTITY", nullable=false)
    @NotNull
    private Integer    quantity     ;

    @Column(name="PRICE", nullable=false)
    @NotNull
    private BigDecimal price        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="BOOK_ORDER_ID", referencedColumnName="ID", insertable=false, updatable=false)
    private BookOrder  bookOrder   ;

    @ManyToOne
    @JoinColumn(name="BOOK_ID", referencedColumnName="ID", insertable=false, updatable=false)
    private Book       book        ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AaaaBookOrderItemFoo()
    {
		super();
		this.compositePrimaryKey = new AaaaBookOrderItemFooKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setBookOrderId( Integer bookOrderId )
    {
        this.compositePrimaryKey.setBookOrderId( bookOrderId ) ;
    }
    public Integer getBookOrderId()
    {
        return this.compositePrimaryKey.getBookOrderId() ;
    }
    public void setBookId( Integer bookId )
    {
        this.compositePrimaryKey.setBookId( bookId ) ;
    }
    public Integer getBookId()
    {
        return this.compositePrimaryKey.getBookId() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : QUANTITY ( INTEGER ) 
    public void setQuantity( Integer quantity )
    {
        this.quantity = quantity;
    }
    public Integer getQuantity()
    {
        return this.quantity;
    }

    //--- DATABASE MAPPING : PRICE ( DECIMAL ) 
    public void setPrice( BigDecimal price )
    {
        this.price = price;
    }
    public BigDecimal getPrice()
    {
        return this.price;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setBookOrder( BookOrder bookOrder )
    {
        this.bookOrder = bookOrder;
    }
    public BookOrder getBookOrder()
    {
        return this.bookOrder;
    }

    public void setBook( Book book )
    {
        this.book = book;
    }
    public Book getBook()
    {
        return this.book;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------

    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        sb.append(quantity);
        sb.append("|");
        sb.append(price);
        return sb.toString(); 
    } 

}
